font_family      family='GeistMono Nerd Font Mono' postscript_name=GeistMonoNFM-Regular
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 15.0
disable_ligatures always
font_features GeistMonoNFM-Regular -calt -liga -dlig

cursor_shape block

copy_on_select clipboard

enable_audio_bell no

window_padding_width 20.0

shell_integration no-cursor

macos_option_as_alt left

map shift+enter send_text all \x1b[13;2u



